# -*- coding: utf-8 -*-
"""Quincena25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apu9efKOrgZPWOHLW9DJpOjyC_iFX1tD
"""

!ngrok config add-authtoken 38aFV2TyU1wpmGoPXv6xuv6OovU_TQrAVmi3gEmwwE8VLgD2

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from datetime import datetime
# 
# st.title("Cálculo de Bonificación")
# 
# # Entradas del usuario
# fecha_contrato = st.date_input("Fecha de inicio de contrato")
# salario = st.number_input("Salario mensual", min_value=0.0, step=0.01)
# 
# # Parámetros fijos
# fecha_fin = datetime(2026, 1, 15)   # Fecha fin de cálculo
# total_dias = 365                    # Días del año
# 
# if fecha_contrato and salario > 0:
#     # Convertir fecha_contrato (date) a datetime
#     fecha_contrato_dt = datetime.combine(fecha_contrato, datetime.min.time())
# 
#     # Calcular cantidad de días trabajados (incluyendo último día)
#     dias_trabajados = (fecha_fin - fecha_contrato_dt).days + 1
# 
#     # Calcular salario aplicable
#     salario_aplicable = salario / 2
# 
#     # Proporción de días
#     proporcion_dias = dias_trabajados / total_dias
# 
#     # Bonificación
#     bonificacion = salario_aplicable * proporcion_dias
# 
#     # Mostrar resultados
#     st.write("### Resultados del cálculo")
#     st.write(f"- Salario ingresado: ${salario:,.2f}")
#     st.write(f"- Fecha inicio contrato: {fecha_contrato.strftime('%d/%m/%Y')}")
#     st.write(f"- Fecha fin cálculo: {fecha_fin.strftime('%d/%m/%Y')}")
#     st.write(f"- Salario aplicable (Salario / 2): ${salario_aplicable:,.2f}")
#     st.write(f"- Cantidad de días: {dias_trabajados}")
#     st.write(f"- Proporción de días: {proporcion_dias:.4f}")
# 
#     st.success(f"### Bonificación: ${bonificacion:,.2f}")

# Crear archivo requirements.txt automáticamente
with open("requirements.txt", "w") as f:
    f.write("streamlit\n")

print("Archivo requirements.txt creado con éxito")

from google.colab import files
files.download("requirements.txt")

from pyngrok import ngrok
import time

# Cerrar túneles previos si existen
ngrok.kill()

# Crear túnel público
public_url = ngrok.connect(8501)
print("Tu aplicación estará disponible en:", public_url)

# Lanzar Streamlit en segundo plano
!streamlit run app.py &

# Esperar unos segundos para que cargue
time.sleep(10)